version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - financial_network

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=financial_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - financial_network

  data_ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    command: python data_ingestion/api.py
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=postgres
    networks:
      - financial_network

  real_time_processing:
    build:
      context: .
      dockerfile: Dockerfile
    command: python real_time_processing/api.py
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
      - data_ingestion
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=postgres
    networks:
      - financial_network

  data_storage:
    build:
      context: .
      dockerfile: Dockerfile
    command: python data_storage/api.py
    ports:
      - "5003:5003"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    networks:
      - financial_network

  data_analysis:
    build:
      context: .
      dockerfile: Dockerfile
    command: python data_analysis/api.py
    ports:
      - "5004:5004"
    depends_on:
      - data_storage
    environment:
      - DB_HOST=postgres
    networks:
      - financial_network

  data_visualization:
    build:
      context: .
      dockerfile: Dockerfile
    command: python data_visualization/app.py
    ports:
      - "5000:5000"
    depends_on:
      - data_analysis
      - data_ingestion
      - data_storage
    environment:
      - DB_HOST=postgres
    networks:
      - financial_network

networks:
  financial_network:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data: 